site_name: Projet de Démo MkDocs
site_author: Angie Pons
site_description: Une démonstration de la puissance de MkDocs avec le thème Material.
repo_url: https://github.com/elishaya13/mon-projet-demo-mkdocs

extra:
  version:
    provider: mike

theme:
  name: material
  language: fr
  logo: assets/logo_mkdocs.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - 'Accueil': index.md
  - 'Changelog': CHANGELOG.md
  - 'Guide de démarrage':
    - 'Installation': guide/installation.md
    - 'Configuration': guide/configuration.md
    - 'Déploiement sur Github': guide/deploiement-github.md
  - 'Fonctionnalités':
    - 'Admonitions': fonctionnalités/admonitions.md
    - 'Blocs de code': fonctionnalités/blocs-de-code.md
    - 'Diagrammes (Mermaid)': fonctionnalités/diagrammes.md
    - 'Onglets de contenu': fonctionnalités/onglets.md
    - 'Annotations': fonctionnalités/annotations.md
    - 'Images': fonctionnalités/images.md
    - 'Grilles': fonctionnalités/grilles.md
    - 'Tableaux de données': fonctionnalités/tableaux.md
