# Informations générales du site
site_name: Projet de Démo MkDocs
site_author: Angie Pons
site_description: Une démonstration de la puissance de MkDocs avec le thème Material.

extra:
  version: 1.0.0

# Lien vers le dépôt
repo_url: https://github.com/elishaya13/mon-projet-demo-mkdocs

# --- Thème et fonctionnalités ---
theme:
  name: material
  language: fr
  logo: assets/logo_mkdocs.png
  palette:
    # Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    # Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.code.annotate

# --- Extensions Markdown ---
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.smartsymbols
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  # Configuration spéciale pour Mermaid avec Material
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# --- Plugins ---
plugins:
  - search
  # Le plugin mermaid2 n'est plus nécessaire ici car Material le gère

# --- Structure de la navigation ---
nav:
  - 'Accueil': index.md
  - 'Changelog': CHANGELOG.md
  - 'Guide de démarrage':
    - 'Installation': guide/installation.md
    - 'Configuration': guide/configuration.md
    - 'Déploiement sur Github' : guide/deploiement-github.md
  - 'Fonctionnalités':
    - 'Admonitions': fonctionnalités/admonitions.md
    - 'Blocs de code': fonctionnalités/blocs-de-code.md
    - 'Diagrammes (Mermaid)': fonctionnalités/diagrammes.md
    - 'Onglets de contenu': fonctionnalités/onglets.md
    - 'Annotations': fonctionnalités/annotations.md
    - 'Images': fonctionnalités/images.md
    - 'Grilles': fonctionnalités/grilles.md
    - 'Tableaux de données' : fonctionnalités/tableaux-de-données.md
