name: Deploy MkDocs site with Mike

on:
  workflow_dispatch: # Déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupère le code de votre dépôt
      - uses: actions/checkout@v4

      # 2. Installe Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Installe Mike et toutes les dépendances de votre thème
      - name: Install dependencies
        run: pip install mkdocs-material mike pymdown-extensions mkdocs-mermaid2-plugin

      # 4. Déploie la version 1.0.0 et la met comme version "latest"
      - name: Deploy with Mike
        run: mike deploy 1.0.0 latest --push --update-aliases -m "Déploiement de la version 1.0.0"
