name: Deploy MkDocs site with Mike

on:
  workflow_dispatch:
  
permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupère le code de votre dépôt
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Installe Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Installe les dépendances
      - name: Install dependencies
        run: pip install mkdocs-material mike pymdown-extensions mkdocs-mermaid2-plugin

      # 4. Configure l'auteur pour Git (ÉTAPE AJOUTÉE)
      - name: Configure Git author
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      # 5. Déploie avec Mike
      - name: Deploy with Mike
        run: mike deploy 1.0.0 latest --push --update-aliases -m "Déploiement de la version 1.0.0"
